name: Update steam playtime

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "10 * * * *"

jobs:
  build:
    name: Update-steam-playtime
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 62fa160542e61ac240820bc0b02b5632
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Clone and run steam-box
        run: |-
          git clone https://github.com/journey-ad/steam-box.git
          cd steam-box && go build -o steam ./cmd/box/main.go
          mv ./steam ../ && cd .. && rm -rf steam-box/
      - name: Commit and push
        run: |-
          ./steam
          git config --global user.email "bot@github.com" && git config --global user.name "Steam-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull --rebase && git push
